# Generated by Django 4.0.6 on 2022-07-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('liked_type', models.ForeignKey(editable=False, limit_choices_to=models.Q(models.Q(('app_label', 'lists'), ('model', 'List')), models.Q(('app_label', 'posts'), ('model', 'Post')), models.Q(('app_label', 'comments'), ('model', 'Comment')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='likes', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='likes', to='accounts.account')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
            },
        ),
    ]
