# Generated by Django 5.0.7 on 2024-08-08 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('liked_type', models.ForeignKey(editable=False, limit_choices_to=models.Q(models.Q(('app_label', 'lists'), ('model', 'list')), models.Q(('app_label', 'posts'), ('model', 'post')), models.Q(('app_label', 'comments'), ('model', 'comment')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'unique_together': {('user', 'liked_type', 'liked_id')},
            },
        ),
    ]
