# Generated by Django 5.0.7 on 2024-08-08 14:32

import accounts.managers
import accounts.validators.username
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('username', models.CharField(error_messages={'unique': 'A user with this username already exists.'}, max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'The username must contain at least %(limit_value)d characters.'), django.core.validators.RegexValidator('^[a-zA-Z0-9\\_]*$', 'The username must contain only letters, numbers and underscore.', 'invalid_character'), django.core.validators.RegexValidator('^[a-zA-Z].*$', 'The username can only start with a letter.', 'invalid_start_character'), accounts.validators.username.RestrictedWordsValidator('A user with this username already exists.', 'restricted_word')])),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('bio', models.CharField(blank=True, max_length=140)),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='images/account_avatars')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ['-id'],
            },
            managers=[
                ('objects', accounts.managers.AccountManager()),
            ],
        ),
    ]
