# Generated by Django 4.0.6 on 2022-07-14 14:51

import accounts.username_validation
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import phonenumber_field.modelfields
from django.contrib.postgres.operations import CITextExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', django.contrib.postgres.fields.citext.CICharField(error_messages={'unique': 'A user with this username already exists.'}, max_length=32, unique=True, validators=[accounts.username_validation.validate_username])),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('bio', models.CharField(blank=True, max_length=140)),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A user with this phone-number already exists.'}, max_length=128, region=None, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(null=True)),
                ('avatar', models.ImageField(null=True, upload_to='account_avatars')),
                ('header', models.ImageField(null=True, upload_to='account_headers')),
                ('access_level', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0)),
                ('birth_date_access_level', models.PositiveSmallIntegerField(choices=[(0, 'Just User'), (1, 'Public Year'), (2, 'Public All')], default=0)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('signup_ip', models.GenericIPAddressField(editable=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
    ]
