# Generated by Django 4.1.3 on 2023-03-31 16:44

import accounts.validators.username
import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(error_messages={'unique': 'A user with this username already exists.'}, max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'The username must contain at least %(limit_value)d characters.'), django.core.validators.RegexValidator('^[a-zA-Z0-9\\_]*$', 'The username must contain only letters, numbers and underscore.', 'invalid_character'), django.core.validators.RegexValidator('^[a-zA-Z].*$', 'The username can only start with a letter.', 'invalid_start_character'), accounts.validators.username.RestrictedWordsValidator('A user with this username already exists.', 'restricted_word')]),
        ),
    ]
