# Generated by Django 4.0.6 on 2022-07-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_signup_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/account_avatars'),
        ),
        migrations.AlterField(
            model_name='account',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='images/account_headers'),
        ),
    ]
