# Generated by Django 4.0.6 on 2022-07-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_avatar_alter_account_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-id'], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
    ]
