# Generated by Django 4.0.6 on 2022-07-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='deleted',
        ),
    ]
