# Generated by Django 4.0.6 on 2022-07-30 13:38

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_date_joined_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.models.UserSoftDeleteManager()),
            ],
        ),
    ]
