# Generated by Django 4.0.6 on 2022-07-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='joined',
        ),
    ]
