# Generated by Django 4.0.6 on 2022-07-30 15:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_account_first_name_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A user with this phone-number already exists.'}, max_length=128, null=True, region=None, unique=True),
        ),
    ]
