# Generated by Django 4.1 on 2022-12-02 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('followed_type', models.ForeignKey(editable=False, limit_choices_to=models.Q(models.Q(('app_label', 'accounts'), ('model', 'account')), models.Q(('app_label', 'lists'), ('model', 'list')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'follow',
                'verbose_name_plural': 'follows',
            },
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('followed_id', models.F('user_id')), ('followed_type_id', 8), _negated=True), name='prevent_self_following'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'followed_type', 'followed_id')},
        ),
    ]
