# Generated by Django 4.0.6 on 2022-08-09 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('followed_type', models.ForeignKey(editable=False, limit_choices_to=models.Q(models.Q(('app_label', 'accounts'), ('model', 'Account')), models.Q(('app_label', 'lists'), ('model', 'List')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'follow',
                'verbose_name_plural': 'follows',
                'unique_together': {('user', 'followed_type', 'followed_id')},
            },
        ),
    ]
