# Generated by Django 4.1.3 on 2023-05-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('followed_id', models.F('user_id')), ('followed_type_id', 8), _negated=True), name='prevent_self_following'),
        ),
    ]
