# Generated by Django 4.0.6 on 2022-07-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0005_account_deleted_at'),
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed_type',
            field=models.ForeignKey(editable=False, limit_choices_to=models.Q(models.Q(('app_label', 'accounts'), ('model', 'Account')), models.Q(('app_label', 'lists'), ('model', 'List')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='accounts.account'),
        ),
    ]
