# Generated by Django 4.1 on 2022-09-08 13:30

from accounts.models import Account
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models


def get_account_content_type_id():
    return ContentType.objects.get_for_model(Account).id


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('followed_id', models.F('user_id')), ('followed_type_id', get_account_content_type_id()), _negated=True), name='prevent_self_following'),
        ),
    ]
