# Generated by Django 5.0.7 on 2024-08-08 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('follows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('followed_id', models.F('user_id')), ('followed_type_id', 8), _negated=True), name='prevent_self_following'),
        ),
    ]
