# Generated by Django 4.0.6 on 2022-07-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_alter_follow_followed_type_alter_follow_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='user',
        ),
    ]
