# Generated by Django 5.2.17 on 2026-08-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_follow_prevent_self_following'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='prevent_self_following',
        ),
    ]
