# Generated by Django 4.0.3 on 2022-04-07 18:45

import account.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=140)),
                ('header', models.ImageField(null=True, upload_to='list')),
                ('access_level', models.IntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0)),
                ('who_add', models.IntegerField(choices=[(0, 'Every One'), (1, 'Just User')], default=0)),
                ('who_reply', models.IntegerField(choices=[(0, 'Every One'), (1, 'Just User')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(editable=False, on_delete=models.SET(account.models.Account.get_sentinel_user), related_name='owned_lists', to='account.account')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
            },
        ),
    ]
