# Generated by Django 4.0.6 on 2022-07-14 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_level', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0)),
                ('who_reply', models.PositiveSmallIntegerField(choices=[(0, 'Every One'), (1, 'Just User')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('created_in', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='lists.list')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='TextValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'text value',
                'verbose_name_plural': 'text values',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_post', models.PositiveIntegerField()),
                ('order_number', models.PositiveIntegerField()),
                ('key', models.CharField(blank=True, max_length=50)),
                ('post', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='posts.post')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'unique_together': {('post', 'id_in_post'), ('post', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_property', models.PositiveIntegerField()),
                ('order_number', models.PositiveIntegerField()),
                ('key', models.CharField(blank=True, max_length=50)),
                ('value_id', models.PositiveIntegerField()),
                ('property', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='pairs', to='posts.property')),
                ('value_type', models.ForeignKey(editable=False, limit_choices_to=models.Q(('app_label', 'post'), ('model', 'TextValue')), on_delete=django.db.models.deletion.PROTECT, related_name='pairs', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'pair',
                'verbose_name_plural': 'pairs',
                'unique_together': {('property', 'order_number'), ('property', 'id_in_property')},
            },
        ),
    ]
