# Generated by Django 5.0.7 on 2024-08-08 13:50

import baseapp.uuid_generator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1023)),
            ],
            options={
                'verbose_name': 'text value',
                'verbose_name_plural': 'text values',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('uuid', models.CharField(db_index=True, default=baseapp.uuid_generator.uuid_generator, editable=False, max_length=11, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('added_to', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='lists.list')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(default=baseapp.uuid_generator.uuid_generator, editable=False, max_length=11)),
                ('order_number', models.PositiveIntegerField()),
                ('key', models.CharField(blank=True, max_length=50)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Text')])),
                ('post', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='posts.post')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'unique_together': {('post', 'order_number'), ('post', 'puuid')},
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField()),
                ('key', models.CharField(blank=True, max_length=50)),
                ('value_id', models.PositiveIntegerField()),
                ('value_type', models.ForeignKey(editable=False, limit_choices_to=models.Q(('app_label', 'post'), ('model', 'TextValue')), on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='contenttypes.contenttype')),
                ('property', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='posts.property')),
            ],
            options={
                'verbose_name': 'pair',
                'verbose_name_plural': 'pairs',
                'unique_together': {('property', 'order_number')},
            },
        ),
    ]
