# Generated by Django 4.0.6 on 2022-07-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_options'),
        ('posts', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_in',
            new_name='added_to',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.account', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='who_reply',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Every One'), (1, 'Just Me')], default=0),
        ),
    ]
