# Generated by Django 4.0.6 on 2022-07-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options_rename_created_in_post_added_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textvalue',
            name='text',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
