# Generated by Django 4.0.6 on 2022-07-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_textvalue_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together={('property', 'order_number')},
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('post', 'order_number')},
        ),
        migrations.RemoveField(
            model_name='pair',
            name='id_in_property',
        ),
        migrations.RemoveField(
            model_name='property',
            name='id_in_post',
        ),
    ]
