# Generated by Django 4.0.6 on 2022-07-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lists', '0006_alter_list_user'),
        ('accounts', '0005_account_deleted_at'),
        ('posts', '0007_post_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='property',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='posts.property'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='value_type',
            field=models.ForeignKey(editable=False, limit_choices_to=models.Q(('app_label', 'post'), ('model', 'TextValue')), on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='post',
            name='added_to',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='lists.list'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.account', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='property',
            name='post',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='posts.post'),
        ),
    ]
