# Generated by Django 4.0.6 on 2022-07-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_pair_property_alter_pair_value_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deleted',
        ),
    ]
