# Generated by Django 4.0.6 on 2022-07-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together={('property', 'order_number')},
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('post', 'order_number')},
        ),
        migrations.AddField(
            model_name='pair',
            name='id_in_property',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='id_in_post',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together={('property', 'id_in_property'), ('property', 'order_number')},
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('post', 'order_number'), ('post', 'id_in_post')},
        ),
    ]
