# Generated by Django 4.0.6 on 2022-07-31 18:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_pair_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('post', 'order_number')},
        ),
        migrations.AddField(
            model_name='property',
            name='puuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('post', 'order_number'), ('post', 'puuid')},
        ),
        migrations.RemoveField(
            model_name='property',
            name='id_in_post',
        ),
    ]
