# Generated by Django 4.0.6 on 2022-07-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_property_unique_together_property_puuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Text')], default=0),
            preserve_default=False,
        ),
    ]
