# Generated by Django 4.0.6 on 2022-07-31 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_property_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together={('property', 'id_in_property')},
        ),
        migrations.RemoveField(
            model_name='pair',
            name='order_number',
        ),
    ]
