# Generated by Django 4.0.6 on 2022-08-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_pair_unique_together_remove_pair_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='id_in_property',
            new_name='order_number',
        ),
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together={('property', 'order_number')},
        ),
    ]
