# Generated by Django 5.0.7 on 2024-08-08 13:50

import baseapp.uuid_generator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('uuid', models.CharField(db_index=True, default=baseapp.uuid_generator.uuid_generator, editable=False, max_length=11, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('header', models.ImageField(blank=True, default=None, null=True, upload_to='images/list_headers')),
                ('who_can_add_post', models.PositiveSmallIntegerField(choices=[(1, 'Just Me'), (2, 'Everyone')], default=1)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'ordering': ['-id'],
            },
        ),
    ]
