# Generated by Django 4.0.6 on 2022-08-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='header',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/list_headers'),
        ),
    ]
