# Generated by Django 4.1.3 on 2023-05-12 20:20

import baseapp.uuid_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='uuid',
            field=models.CharField(db_index=True, default=baseapp.uuid_generator.uuid_generator, editable=False, max_length=11, unique=True),
        ),
    ]
