# Generated by Django 4.1.3 on 2023-07-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_list_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='who_can_add_post',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Just Me'), (2, 'Everyone')], default=1),
        ),
    ]
