# Generated by Django 4.0.6 on 2022-07-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='list',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='images/list_headers'),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
