# Generated by Django 4.0.6 on 2022-07-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_options'),
        ('lists', '0003_alter_list_description_alter_list_header_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-id'], 'verbose_name': 'list', 'verbose_name_plural': 'lists'},
        ),
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.account', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='list',
            name='who_add',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Every One'), (1, 'Just Me')], default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='who_reply',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Every One'), (1, 'Just Me')], default=0),
        ),
    ]
