# Generated by Django 4.0.6 on 2022-07-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_alter_list_options_alter_list_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
