# Generated by Django 4.0.6 on 2022-07-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_deleted_at'),
        ('lists', '0005_list_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.account', verbose_name='user'),
        ),
    ]
