# Generated by Django 4.0.6 on 2022-07-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_list_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='deleted',
        ),
    ]
