# Generated by Django 4.1.3 on 2023-05-12 19:49

import baseapp.uuid_generator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('uuid', models.CharField(db_index=True, default=baseapp.uuid_generator.uuid_generator, editable=False, max_length=13, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.CharField(blank=True, max_length=1023)),
                ('replied_to_id', models.PositiveIntegerField(editable=False)),
                ('replied_to_type', models.ForeignKey(editable=False, limit_choices_to=models.Q(models.Q(('app_label', 'lists'), ('model', 'list')), models.Q(('app_label', 'posts'), ('model', 'post')), models.Q(('app_label', 'comments'), ('model', 'comment')), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['-id'],
            },
        ),
    ]
