# Generated by Django 4.0.6 on 2022-07-14 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_level', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0)),
                ('who_reply', models.PositiveSmallIntegerField(choices=[(0, 'Every One'), (1, 'Just User')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('body', models.CharField(blank=True, max_length=1000)),
                ('replied_to_id', models.PositiveIntegerField()),
                ('replied_to_type', models.ForeignKey(editable=False, limit_choices_to=models.Q(models.Q(('app_label', 'lists'), ('model', 'List')), models.Q(('app_label', 'posts'), ('model', 'Post')), models.Q(('app_label', 'comments'), ('model', 'Comment')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
