# Generated by Django 4.0.6 on 2022-07-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_options'),
        ('comments', '0003_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='replied_to_id',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.account', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='who_reply',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Every One'), (1, 'Just Me')], default=0),
        ),
    ]
