# Generated by Django 4.0.6 on 2022-07-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_replied_to_type_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted',
        ),
    ]
