# Generated by Django 4.0.6 on 2022-07-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comments', '0007_remove_comment_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replied_to_type',
            field=models.ForeignKey(editable=False, limit_choices_to=models.Q(models.Q(('app_label', 'lists'), ('model', 'List')), models.Q(('app_label', 'posts'), ('model', 'Post')), models.Q(('app_label', 'comments'), ('model', 'Comment')), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='contenttypes.contenttype'),
        ),
    ]
